name: Deploy

on:
  release:
    types: [created]

env:
  PYTHONUNBUFFERED: 1

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: 
      name: pypi
      url: https://pypi.org/p/spotifyconnector

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-deploy-${{ hashFiles('**/setup.py', '**/Pipfile.lock') }}

      - name: Install build and deployment tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Verify package integrity
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
