name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONUNBUFFERED: 1

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/setup.py', '**/Pipfile.lock') }}

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install black isort flake8 pylint

      - name: Install package for linting
        run: pip install -e .

      - name: Check code formatting with Black
        run: python -m black --check --diff spotifyconnector/ tests/

      - name: Check import sorting with isort
        run: python -m isort --check-only --diff spotifyconnector/ tests/

      - name: Run flake8 style checks
        run: python -m flake8 spotifyconnector/ --max-line-length=88 --extend-ignore=E203,W503

      - name: Run pylint code analysis
        run: python -m pylint spotifyconnector/ --rcfile=./pylintrc
        continue-on-error: true
